import Head from "next/head";
import styled from "styled-components";
import { useAccount } from "wagmi";
import ConnectView from "../components/ConnectView";
import GameView from "../components/GameView";

const Layout = styled.main`
  min-height: 100vh;
  display: flex;
  align-items: stretch;

  > * {
    flex: 1;
  }
`;

export default function Home() {
  const { address } = useAccount();

  return (
    <>
      <Head>
        <title>King of the hill</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>{address ? <GameView /> : <ConnectView />}</Layout>
    </>
  );
}
